{
 "title": "Accelerator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"accelerator\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field == \"current\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GeV" } },
   "targets": [
    {
     "query": "from(bucket: \"accelerator\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Fillint Pattern",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bunches" } },
   "targets": [
    {
     "query": "from(bucket: \"accelerator\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field == \"pattern\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  }
 ]
}