{
 "title": "HYPS monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "BGO temp",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"mppchv\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"mppchv\")\n//   // |> map(fn: (r) => ({ r with mppchv: strings.toUpper(v: r.mppchv) }))\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"_field\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group(columns: [])\n |> sort(columns: [\"ip\", \"channel\"])\n// //  |> keep(columns: [\"_time\", \"mppchv\", \"cmon\", \"cset\", \"pol\"])\n  |> keep(columns: [\"ip\", \"channel\", \"name\", \"vset\", \"vmon\", \"iset\", \"imon\", \"status\", \"temp\", \"trip\"])\n"
    }
   ]
  },
  { "title": "Accelerator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"accelerator\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._field == \"mode\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"accelerator\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"current\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "GeV" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"accelerator\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r._field == \"energy\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Air",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "BGO temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"logger\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field == \"value\")\n  |> drop(columns: [\"unit\", \"host\", \"dest_bucket\", \"environment\"])\n  |> last()"
    }
   ]
  },
  { "title": "HDDAQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hddaq\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._field == \"runnumber\")\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\", \"_field\"])\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hddaq\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._field == \"starttime\")\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\", \"_field\"])\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hddaq\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._field == \"trig\")\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\", \"_field\"])\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hddaq\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._field == \"comment\")\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\", \"_field\"])\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field == \"param_file\")\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\", \"_field\"])\n  |> last()"
    }
   ]
  }
 ]
}