{
 "title": "System resource",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "cpu-total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage_user\" and r.cpu == \"cpu-total\")\n//  |> aggregateWindow(every: 10s, fn: mean)\n//  |> group(columns: [\"host\"])\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"net\")\n  |> filter(fn: (r) => r._field == \"bytes_sent\" or r._field == \"bytes_recv\")\n  |> derivative(unit: 1s) //, nonNegative: true)\n//  |> group(columns: [\"host\"])\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"interface\"])\n  |> yield(name: \"network_bandwidth\")\n"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\")\n//  |> aggregateWindow(every: 10s, fn: mean)\n//  |> group(columns: [\"host\"])\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"disk\" and (r._field == \"used\" or r._field == \"free\"))\n//  |> aggregateWindow(every: 10s, fn: mean)\n//  |> group(columns: [\"host\"])\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"path\"])\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "diskio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"diskio\" and (r._field == \"read_bytes\" or r._field == \"write_bytes\"))\n  |> derivative(unit: 1s) //, nonNegative: true)\n//  |> aggregateWindow(every: 10s, fn: mean)\n//  |> group(columns: [\"host\"])\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"name\"])\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "cpu temp.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"system\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"sensors\" and r._field == \"temp_input\")\n  |> filter(fn: (r) => (r.chip =~ /coretemp.*/ and r.feature =~ /package.*/) or r.chip =~ /k10temp.*/)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\n  |> yield()\n"
    }
   ]
  }
 ]
}