{
 "title": "Target",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"target\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field =~ /alert.*/)\n  |> last()\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"target\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field =~ /temp_.*/)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "H2 pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Torr" } },
   "targets": [
    {
     "query": "from(bucket: \"target\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field =~ /h2_.*/)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Vacuum CC10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "query": "from(bucket: \"target\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field =~ /vacuum_.*/)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Heater voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"target\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._field =~ /heater*/)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  }
 ]
}