{
 "title": "Trigger",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Trigger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"param_file\", \"sel_tof\"])\n  |> limit(n: 1)\n "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"param_file\", \"sel_tof\"])\n  |> limit(n: 1)\n "
    }
   ]
  },
  {
   "title": "large",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last update",
     "type": "stat",
     "gridPos": { "h": 3, "w": 13, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field == \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"_time\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "param_file",
     "type": "stat",
     "gridPos": { "h": 3, "w": 11, "x": 13, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field == \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigA",
     "type": "stat",
     "gridPos": { "h": 3, "w": 13, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigA PS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 13, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigA Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigB",
     "type": "stat",
     "gridPos": { "h": 3, "w": 13, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigB PS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 13, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigB Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigC",
     "type": "stat",
     "gridPos": { "h": 3, "w": 13, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigC PS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 13, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigC Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 13, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigD PS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 13, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigD Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigE",
     "type": "stat",
     "gridPos": { "h": 3, "w": 13, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigE PS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 13, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigE Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigF",
     "type": "stat",
     "gridPos": { "h": 3, "w": 13, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigF PS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 13, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "TrigF Gate",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"trigger\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_time\", \"sel_tof\"])\n  |> limit(n: 1)\n "
      }
     ]
    },
    {
     "title": "Register",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "query": "from(bucket: \"trigger\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement == \"register\" and r._field != \"param_file\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> drop(columns: [\"param_file\"])\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> limit(n: 10)\n "
      }
     ]
    }
   ]
  }
 ]
}