from(bucket: "runsummary")
  |> range(start: 0)
  // |> filter(fn: (r) => r._measurement == "trigger" and r.host == "eb-hyps.monitor.hypsnet")
    // |> filter(fn: (r) => r._field == "run_number")
//  |> sort(columns: ["_time"], desc: true)
  // |> last()
//  |> group()
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
//  |> drop(columns: ["_time", "param_file", "sel_tof"])
//  |> limit(n: 1)
